plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {

    // Cucumber
    testImplementation platform('io.cucumber:cucumber-bom:7.34.6')
    testImplementation 'io.cucumber:cucumber-java'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine'

    // JUnit
    testImplementation platform('org.junit:junit-bom:6.1.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.junit.platform:junit-platform-suite'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Selenium
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.46.0'
}

test {
    useJUnitPlatform()
}